spring:
  application:
    name: api-gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: chat-websocket
          uri: lb://chat-websocket
          predicates:
            - Path=/api/chat

        - id: user-servi
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:9090/realms/ChatApplication
#        registration:
#          keycloak:
#            client-id: api-gateway
#            client-secret: 29e0UjZTAhzHYl8MxhqddliacKYN6Pvu
#            authorization-grant-type: authorization_code
#            authorization-uri: http://localhost:9090/realms/ChatApplication/protocol/openid-connect/auth
#            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
#            scope: openid

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:9090/realms/ChatApplication


server:
  port: 8080
